name: SmartLogic
timezone: America/New_York
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
markdown: kramdown
highlighter: 'rouge'
sass:
  sass_dir: _sass
  style: :compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-redirect-from
