name: SmartLogic
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Procfile'
  - 'README.md'
  - 'Guardfile'
markdown: kramdown
highlighter: null
sass:
  sass_dir: _sass
  style: :compressed
navigation:
- title: About
  url: /about.html
  subnav:
  - title: Four keys to building smarter software
    anchor: /abount.html#four-keys
  - title: Types of clients we work with
    anchor: /abount.html#types-of-clients
  - title: The Team
    anchor: /abount.html#team
- title: Experience
  url: /experience.html
- title: Smart Thinking
  url: /smart-thinking.html
- title: Get In Touch
  url: /get-in-touch.html
- title: What makes us different
  url: /what-makes-us-different.html
