name: SmartLogic
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Procfile'
  - 'README.md'
  - 'Guardfile'
markdown: kramdown
highlighter: null
sass:
  sass_dir: _sass
  style: :compressed
navigation:
- title: About
  url: /about.html
  subnavigation:
  - title: Four keys to building smarter software.
    anchor: four-keys
  - title: Who we work with.
    anchor: who-we-work-with
  - title: The Team.
    anchor: the-team
- title: Experience
  url: /experience.html
  subnavigation:
  - title: Case Studies
    anchor: case-studies
  - title: Areas of Expertise
    anchor: areas-of-expertise
  - title: Let's Work Together
    anchor: lets-work-together
- title: Smart Thinking
  url: /smart-thinking.html
  subnavigation:
  - title: Community
    anchor: community
- title: Get In Touch
  url: /get-in-touch.html
  subnavigation:
  - title: Work With Us
    anchor: work-with-us
  - title: Our Office
    anchor: our-office
  - title: Location
    anchor: location
- title: What makes us different
  url: /what-makes-us-different.html
