name: SmartLogic
timezone: America/New_York
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
markdown: kramdown
highlighter: 'rouge'
sass:
  sass_dir: _sass
  style: :compressed
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

page_gen:
  - index_files: true
    data: elixir_wizards_episodes
    template: podcast-episode
    name: slug
    dir: podcast/elixir-wizards/

url: "https://smartlogic.io"
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
