name: Pages Publish
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: rss-data-updated
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yqq git build-essential

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Setup ruby
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Generate site
      run: |
        bundle exec jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

    - name: Setup SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.DEPLOY_KNOWN_HOSTS }}

    - name: Update Deployment
      run: |
        ssh deploy@161.35.119.31 \
          -o IdentitiesOnly=yes \
          -C "cd sites/smartlogic.io && git pull origin gh-pages"
