name: Pages Publish
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: rss-data-updated
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yqq git build-essential

    - name: Setup ruby
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Generate site
      run: |
        bundle exec jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

    - name: Update Deployment
      shell: bash
      env:
        DEPLOY_PRIVATE_KEY: ${{secrets.DEPLOY_PRIVATE_KEY}}
      run: |
        echo $DEPLOY_PRIVATE_KEY > ./id_rsa
        chmod 600 ./id_rsa
        ssh deploy@161.35.119.31 -i ./id_rsa \
          -o IdentitiesOnly=yes \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -C "cd sites/smartlogic.io && git pull origin gh-pages"
